# Generated by Django 4.1 on 2024-10-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_name', models.CharField(max_length=40)),
                ('chef_description', models.TextField()),
                ('chef_position', models.CharField(max_length=30)),
                ('chef_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=40)),
                ('pizza_description', models.TextField()),
                ('pizza_image', models.ImageField(upload_to='')),
                ('pizza_created', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=40)),
                ('post_subtitle', models.CharField(max_length=80)),
                ('post_description', models.TextField()),
                ('post_image', models.ImageField(upload_to='')),
                ('post_creator', models.TextField()),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('post_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
