# Generated by Django 4.1 on 2024-10-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_created',
            new_name='pizza_price',
        ),
    ]
